DEF RS_NORMAL_METHOD = u'zig'
DEF RS_RNG_SEED = 1
DEF RS_RNG_ADVANCEABLE = 0
DEF RS_RNG_JUMPABLE = 0
DEF RS_RNG_STATE_LEN = 4
DEF RS_SEED_NBYTES = 2
DEF RS_SEED_ARRAY_BITS = 64
DEF JUMP_DOCSTRING = """
"""