from distutils.core import setup
from distutils.extension import Extension
from os import getcwd
from os.path import join

from Cython.Build import cythonize

with open('config.pxi', 'w') as config:
    config.write('# Autogenerated\n\n')
    for key in ('RNG_DUMMY', 'RNG_PCG_32', 'RNG_PCG_64', 'RNG_RANDOMKIT'):
        val = '1' if key == 'RNG_PCG_64' else '0'
        config.write('DEF ' + key + ' = ' + val + '\n')


pwd = getcwd()

sources = [join(pwd, 'core_rng.pyx')]

sources += [join(pwd, 'src', 'pcg', p) for p in ('pcg-advance-128.c', 'pcg-rngs-128.c')]
sources += [join(pwd, 'shims/pcg-64', 'pcg-64-shim.c')]

defs = [('PCG_64_RNG', '1'), ('PCG_HAS_128BIT_OPS', '1'), ('__SIZEOF_INT128__', '16')]

include_dirs = [pwd]
include_dirs += [join(pwd, 'src', 'pcg')]

setup(ext_modules=cythonize([Extension("core_rng",
                                       sources=sources,
                                       include_dirs=include_dirs,
                                       define_macros=defs,
                                       extra_compile_args=['-std=c99'])
                               ])
)
